# Generated by Django 2.0.4 on 2018-04-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200)),
                ('art_text', models.TextField()),
                ('art_date', models.DateTimeField()),
                ('art_likes', models.IntegerField(default=0)),
                ('art_link', models.TextField()),
            ],
            options={
                'db_table': 'arts',
            },
        ),
        migrations.CreateModel(
            name='Comments_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_arts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Arts')),
            ],
            options={
                'db_table': 'comments_art',
            },
        ),
    ]
