# Generated by Django 2.0.4 on 2018-04-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artfolder_name', models.CharField(default='New folder', max_length=200)),
                ('artfolder_date', models.DateTimeField(null=True)),
                ('artfolder_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artfolder',
            },
        ),
        migrations.AddField(
            model_name='comments_art',
            name='comments_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arts',
            name='art_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='art_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='art_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='arts',
            name='art_title',
            field=models.CharField(default='New art', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments_art',
            name='comments_text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='arts',
            name='art_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.ArtFolder'),
        ),
    ]
